### ISSUE TITLE
Why devDependencies instead of dependencies

### ISSUE THREAD

**Issue by RafalFilipek** [altjs/router#1]
Now I have to install all libraries by myself. Is there any reason why you didn't add them as `dependencies`?

Thanks

**Comment by taion** [comment]
`dependencies` is definitely not right for e.g. `react` and `react-router` (it will actually break stuff).

With NPM3, if this used `peerDependencies`, you'd still have to install those libraries yourself anyway.

**Comment by goatslacker** [comment]
dev dependencies because I require them for testing.

I assume if you're using alt-router then you're probably using react-router, and if you're using react-router then you're using react. Otherwise, wrong library :)

I also assume you're using alt

**Comment by taion** [comment]
Might be useful to specify a 1.0.0-prerelease for `react-router` just to make sure nobody accidentally tries to use this with React-Router v0.13.x.
