### ISSUE TITLE
React router do not seems to recognize alt

### ISSUE THREAD

**Issue by moimael** [altjs/router#2]
Hi,

I tried to make it work following the examples, but every time I load the page I get this : 

```
Warning: Failed Context Types: Required context `flux` was not specified in `AltRouter`.
app.js:109 Uncaught TypeError: object is not a function
```

My code looks like this : 

```
import AltRouter from 'alt-router';
import React from 'react';
import ReactDOM from 'react-dom';
import createBrowserHistory from 'history/lib/createBrowserHistory';
import { Route } from 'react-router';

import alt from './alt';

var App = require('./components/App.jsx');
var Offers = require('./components/Offers.jsx');
var Customers = require('./components/Customers.jsx');


const routes = (
  <Route path="/" component={App}>
    <Route path="customers" component={Customers} />
    <Route path="offers" component={Offers} />
  </Route>
);

ReactDOM.render((<AltRouter flux={alt} history={createBrowserHistory()} routes={routes} />), document.getElementById('app'));
```

and alt.js : 

```
const Alt = require('alt');
const alt = new Alt();

module.exports = alt;
```

Any ideas ?

Thanks !

**Comment by jdlehman** [comment]
I think this is because `AltRouter` is not setting the `flux` context for you.

cc @goatslacker: I am not sure if you wanted `AltRouter` to create the context or not.  If so, I believe something like the following is needed in the `AltRouter` component:

``` js
  getChildContext() {
    return {flux: this.props.flux};
  }
```

**Comment by goatslacker** [comment]
I normally use [this](https://github.com/altjs/react/blob/master/src/supplyFluxContext.js) for that but I'm not opposed to adding it here so you can skip adding yet another component.

**Comment by moimael** [comment]
Yes I think it would make a lot of sense to integrate it,since it is always required and would simplify getting started with alt router.

**Comment by goatslacker** [comment]
I removed the requirement for context, now you can optionally pass it in.
