### ISSUE TITLE
Getting invariant violation and warning(s)

### ISSUE THREAD

**Issue by collinwu** [altjs/router#4]
Not sure what else to try. I spent a decent amount of time seeing if I could debug on my side, but no luck.
Getting an invariant violation and some warning(s). See image below. I've also pasted my router.jsx and dependencies. I have another repo/project that uses almost identical code with slightly older versions and works fine. Any ideas?

<img width="465" alt="screen shot 2015-11-06 at 8 24 13 pm" src="https://cloud.githubusercontent.com/assets/6867357/11013487/c35a32d4-84c4-11e5-91ec-ba155c4cb4f9.png">

My dependencies:

```
"alt": "^0.17.8",
"alt-router": "^1.2.0",
"history": "^1.13.0",
"react": "^0.14.2",
"react-dom": "^0.14.2",
"react-router": "^0.13.5",
"react-tap-event-plugin": "^0.2.1"

```

Here's where AltRouter is used:

``` javascript
import React from 'react';
import { Router, Route, IndexRoute } from 'react-router';
import AltRouter from 'alt-router';
import alt from './libs/alt';
import createBrowserHistory from 'history/lib/createBrowserHistory';

import App from './components/app/App.jsx';

const history = createBrowserHistory();

const routes = (
  <Route path="/" component={App}>
  </Route>
)

export default class AppRouter extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <AltRouter flux={alt} history={history} routes={routes} />
    );
  }
}

export default AppRouter;
```

**Comment by taion** [comment]
You need one of the 1.0.0 prereleases of React Router, not v0.13.5.

@goatslacker Would it make sense to set up a peer dependency here?

**Comment by collinwu** [comment]
switched over to `"react-router": "^1.0.0-rc3"` and it works now! Cheers!

thanks @taion !

should I leave this issue open in case @goatslacker goatslacker wants to comment?

**Comment by goatslacker** [comment]
Yeah peer dependency is fine.
